{{- if .Values.anchoreGlobal.usePreupgradeHook -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "anchore-engine.fullname" . }}-upgrade-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "anchore-engine.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.anchoreGlobal.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.anchoreGlobal.annotations }}
  annotations:
  {{- with .anchoreGlobal.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end -}}