{{- if not .Values.kai.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kai.fullname" . }}
  labels:
    app: {{ template "kai.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.kai.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  KAI_ANCHORE_PASSWORD: {{  .Values.kai.anchore.password }}
{{- end }}
