{{- if not .Values.useExistingSecrets -}}
{{- /*
  If release is being upgraded, don't recreate the defaultAdminPassword, instead get it from the corresponding existing
  secret.
*/ -}}
{{- $anchoreAdminPass := (include "enterprise.defaultAdminPassword" . | quote) -}}
{{- if and .Release.IsUpgrade (not .Values.anchoreConfig.default_admin_password) -}}
  {{- $adminPassSecret := (lookup "v1" "Secret" .Release.Namespace (include "enterprise.fullname" .)) -}}
  {{- if $adminPassSecret -}}
    {{- $anchoreAdminPass = (index $adminPassSecret.data "ANCHORE_ADMIN_PASSWORD" | b64dec) -}}
  {{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "enterprise.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "enterprise.common.labels" . | nindent 4 }}
  annotations: {{- include "enterprise.common.annotations" . | nindent 4 }}
type: Opaque
stringData:
  ANCHORE_ADMIN_PASSWORD: {{ $anchoreAdminPass | quote }}
  ANCHORECTL_PASSWORD: {{ $anchoreAdminPass | quote }}
  ANCHORECLI_PASS: {{ $anchoreAdminPass | quote }}
  ANCHORE_DB_HOST: {{ include "enterprise.dbHostname" .  | quote }}
  ANCHORE_DB_NAME: {{ index .Values "postgresql" "auth" "database" | quote }}
  ANCHORE_DB_USER: {{ index .Values "postgresql" "auth" "username" | quote }}
  ANCHORE_DB_PASSWORD: {{ index .Values "postgresql" "auth" "password" | quote }}
  ANCHORE_DB_PORT: {{ index .Values "postgresql" "primary" "service" "ports" "postgresql" | quote }}
{{- with .Values.anchoreConfig.keys.secret }}
  ANCHORE_SAML_SECRET: {{ . | quote }}
{{- end }}

{{- end -}}
