apiVersion: v1
kind: List
metadata:
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: {{ .Release.Name }}-controller-config
    labels:
      app: {{ template "anchore-admission-controller.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  data:
    config.json: |-
      {
        "validator": {
          "requestanalysis": {{ .Values.requestAnalysis }}
        },
        "AnchoreEndpoint": "{{ .Values.anchoreEndpoint }}",
        "PolicySelectors": {{ toJson .Values.policySelectors }}
      }

- apiVersion: v1
  kind: Service
  metadata:
    name: {{ template "anchore-admission-controller.fullname" . }}
    labels:
      app: {{ template "anchore-admission-controller.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  spec:
    type: {{ .Values.service.type }}
    ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
    selector:
      app: {{ template "anchore-admission-controller.name" . }}
      release: {{ .Release.Name }}

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: {{ template "anchore-admission-controller.fullname" . }}
    labels:
      app: {{ template "anchore-admission-controller.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  spec:
    replicas: {{ .Values.replicaCount }}
    template:
      metadata:
        labels:
          app: {{ template "anchore-admission-controller.name" . }}
          release: {{ .Release.Name }}
      spec:
        serviceAccountName: {{ template "anchore-admission-controller.fullname" . }}
        volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: {{ template "anchore-admission-controller.name" . }}-certs
        - name: controller-config
          configMap:
            name: {{.Release.Name}}-controller-config
        - name: anchore-auth
          secret:
            secretName: {{ .Values.credentialsSecret }}
        containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
          - "/anchore-kubernetes-admission-controller"
          - "--audit-log-path=-"
          - "--tls-cert-file=/var/serving-cert/tls.crt"
          - "--tls-private-key-file=/var/serving-cert/tls.key"
          - "--v={{ .Values.logVerbosity }}"
          ports:
          - containerPort: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.internalPort }}
              scheme: HTTPS
          volumeMounts:
          - mountPath: /var/serving-cert
            name: serving-cert
            readOnly: true
          - mountPath: /config
            name: controller-config
          - mountPath: /credentials
            name: anchore-auth
          env:
          - name: CONFIG_FILE_PATH
            value: /config/config.json
          - name: CREDENTIALS_FILE_PATH
            value: /credentials/credentials.json
          resources:
{{ toYaml .Values.resources | indent 12 }}
  {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
  {{- end }}
  {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
  {{- end }}
  {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
  {{- end }}