apiVersion: v1
kind: List
metadata:
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: {{ .Release.Name }}-controller-config
    labels:
      app: {{ template "anchore-admission-controller.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  data:
    config.json: |-
      {
        "validator": {
          "requireimaganalyzed": {{ .Values.enableAnalysisGating }},
          "requirepasspolicy": {{ .Values.enableStrictGating }},
          "requestanalysis": {{ .Values.requestAnalysis }}
        },

        "client": {
          "endpoint": "{{ .Values.anchore.endpoint }}",
          "policybundle": "{{ .Values.anchore.policybundle }}"
        }
      }

- apiVersion: v1
  kind: Service
  metadata:
    name: {{ template "anchore-admission-controller.fullname" . }}
    labels:
      app: {{ template "anchore-admission-controller.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  spec:
    type: {{ .Values.service.type }}
    ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
    selector:
      app: {{ template "anchore-admission-controller.name" . }}
      release: {{ .Release.Name }}

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: {{ template "anchore-admission-controller.fullname" . }}
    labels:
      app: {{ template "anchore-admission-controller.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  spec:
    replicas: {{ .Values.replicaCount }}
    template:
      metadata:
        labels:
          app: {{ template "anchore-admission-controller.name" . }}
          release: {{ .Release.Name }}
      spec:
        serviceAccountName: {{ template "anchore-admission-controller.fullname" . }}
        volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: {{ template "anchore-admission-controller.name" . }}-certs
        - name: controller-config
          configMap:
            name: {{.Release.Name}}-controller-config
        containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - "/anchore-kubernetes-admission-controller"
          - "--audit-log-path=-"
          - "--tls-cert-file=/var/serving-cert/tls.crt"
          - "--tls-private-key-file=/var/serving-cert/tls.key"
          - "--v={{ .Values.logVerbosity }}"
          ports:
          - containerPort: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.internalPort }}
              scheme: HTTPS
          volumeMounts:
          - mountPath: /var/serving-cert
            name: serving-cert
            readOnly: true
          - mountPath: /config
            name: controller-config
          env:
          - name: CONFIG_FILE_PATH
            value: /config/config.json
          - name: ANCHORE_USERNAME
            {{ if .Values.anchore.credentialsSecret }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.anchore.credentialsSecret }}
                key: username
            {{ else }}
            value: {{ .Values.anchore.username }}
            {{ end }}
          - name: ANCHORE_PASSWORD
            {{ if .Values.anchore.credentialsSecret }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.anchore.credentialsSecret }}
                key: password
            {{ else }}
            value: {{ .Values.anchore.password }}
            {{ end }}

          resources:
{{ toYaml .Values.resources | indent 12 }}
  {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
  {{- end }}
