name: Release Charts to charts.anchore.io

on:
  push:
    branches:
      - main

jobs:
  release:
    env:
      REPO: "${{ github.repository }}"
      REPO_NAME: "${{ github.event.repository.name }}"
      TARGET_BRANCH: "${{ github.event.pull_request.base.ref }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add Anchore Helm repo
        run: |
          helm repo add anchore https://charts.anchore.io/stable
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: stable
          charts_repo_url: https://charts.anchore.io
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
