name: "Test using kind and chart-testing tool"

on:
  - pull_request
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        kubernetesVersion: ["v1.23.17", "v1.24.15", "v1.25.11", "v1.26.6", "v1.27.3"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch history
      run: git fetch --prune --unshallow

    - name: Shellcheck
      uses: ludeeus/action-shellcheck@2.0.0

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.8.0

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.4.0

    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed --config 'ct-config.yaml' --target-branch ${{ github.event.pull_request.base.ref }})
        if [[ -n "$changed" ]]; then
          echo "CHANGED=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Install kind
      if: steps.list-changed.outputs.CHANGED == 'true'
      uses: helm/kind-action@v1.8.0
      with:
        node_image: "kindest/node:${{ matrix.kubernetesVersion }}"
        config: kind-config.yaml
        wait: 600s

    - name: Check kind nodes
      if: steps.list-changed.outputs.CHANGED == 'true'
      run: kubectl describe nodes

    - name: Create pullcreds and license secrets
      if: steps.list-changed.outputs.CHANGED == 'true'
      run: |
        kubectl create namespace anchore
        echo "${ANCHORE_LICENSE}" | base64 --decode > /tmp/anchore-license
        kubectl --namespace anchore create secret generic anchore-enterprise-license --from-file=license.yaml=/tmp/anchore-license
        kubectl --namespace anchore create secret docker-registry anchore-enterprise-pullcreds --docker-server=docker.io --docker-username="${DOCKER_USER}" --docker-password="${DOCKER_PASS}"
      env:
        ANCHORE_LICENSE: ${{ secrets.B64_ANCHORE_LICENSE }}
        DOCKER_USER: ${{ secrets.ANCHORECI_DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.ANCHORECI_DOCKER_PASS }}

    - name: Run chart-testing
      if: steps.list-changed.outputs.CHANGED == 'true'
      run: ct install --config ct-config.yaml
